<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GedCore\GedCore.csproj" />
    <ProjectReference Include="..\GedFire\GedFire.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="TestData\Example-5.5.ged" />
    <EmbeddedResource Include="TestData\Example-7.0.ged" />
    <EmbeddedResource Include="TestData\Extensions-7.0.ged" />
    <EmbeddedResource Include="TestData\Changesets\*.json" />
  </ItemGroup>

</Project>
